### PR TITLE
add event-model maintainers

### PR DESCRIPTION
**Pull request by untzag**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by untzag** [comment]
@conda-forge-admin, please rerender

**Comment by mrakitin** [comment]
Thanks for the PR, @untzag! I am a member of the above-mentioned group, but can't edit the files (seems no permissions were granted).

We have observed that [before](https://github.com/conda-forge/tomviz-feedstock/pull/1), maybe @conda-forge/core could help us with getting the right permissions? Thanks!

**Comment by untzag** [comment]
@mrakitin I think I'm just going to manually add y'all as owners, at least you'll have ownership then. If you figure out why the group doesn't work as intended you can fix it later.

**Comment by mrakitin** [comment]
Sounds great, thanks again @untzag!

**Pull request merged**
